small alterations for repo dispatch with git_token

diff --git a/.github/workflows/ecoli_fbi_workflow.yml b/.github/workflows/ecoli_fbi_workflow.yml
--- a/.github/workflows/ecoli_fbi_workflow.yml
+++ b/.github/workflows/ecoli_fbi_workflow.yml
@@ -3,6 +3,8 @@ name: ecoli food bourne infection workflow
 on:
   push:
     branches: ["main"]
+    tags:
+      - "!**"
   pull_request:
     branches: ["main"]
 
@@ -37,20 +39,32 @@ jobs:
           conda activate ecoli_pipeline
           make test
 
-      # Step 4: Trigger bifrost_sp_ecoli workflow
-      - name: Workflow dispatch with API - trigger bifrost_sp_ecoli workflow 
-        run: |
-          response=$(curl -L \
-          -X POST \
-          -H "Accept: application/vnd.github+json" \
-          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
-          https://api.github.com/repos/ssi-dk/bifrost_sp_ecoli/actions/workflows/bifrost_sp_ecoli_workflow.yml/dispatches \
-          -d '{"event_type":"ecoli-fbi-webhook"}' \
-          --write-out "%{http_code}" -o /dev/null)
-          
-          echo "Status Code: $response"
+      # Step 4: Create tag if test passes
+      #- name: Create tag
+      #  if: ${{ success() }}
+      #  env:
+      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      #  run: |
+      #    TAG_NAME="ecoli_fbi.$('%Y%m%d').${GITHUB_SHA::7}"  # Use the first 7 characters of the commit SHA
+      #    git tag $TAG_NAME
+      #    git push origin $TAG_NAME
+      #    echo "Creating tag: $TAG_NAME"
 
-          if [[ "$response" != *"204"* ]]; then
-            echo "Failed to trigger workflow: $response"
-            exit 1
-          fi
+      # Step 5: Trigger bifrost_sp_ecoli workflow
+      - name: Workflow dispatch with API - trigger bifrost_sp_ecoli workflow 
+        if: ${{ success() }}
+        run: |
+            response=$(curl -L \
+            --request POST \
+            -H "Accept: application/vnd.github.everest-preview+json" \
+            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            https://api.github.com/repos/ssi-dk/bifrost_sp_ecoli/dispatches \
+            -d '{"event_type":"ecoli-fbi-webhook"}'
+            )
+            
+            echo "Status Code: $response"
+
+            if [[ "$response" != *"204"* ]]; then
+              echo "Failed to trigger workflow: $response"
+              exit 1
+            fi
