testing md5sum and error code for curl to check if reporsitory dispatch fails

diff --git a/.github/workflows/ecoli_fbi_workflow.yml b/.github/workflows/ecoli_fbi_workflow.yml
--- a/.github/workflows/ecoli_fbi_workflow.yml
+++ b/.github/workflows/ecoli_fbi_workflow.yml
@@ -40,9 +40,17 @@ jobs:
       # Step 4: Trigger bifrost_sp_ecoli workflow
       - name: Workflow dispatch with API - trigger bifrost_sp_ecoli workflow 
         run: |
-          curl -L \
+          response=$(curl -L \
           -X POST \
-          -H "Accept: application/vnd.github.v3+json" \
-          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+          -H "Accept: application/vnd.github+json" \
+          -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
           https://api.github.com/repos/ssi-dk/bifrost_sp_ecoli/actions/workflows/bifrost_sp_ecoli_workflow.yml/dispatches \
-          -d '{"event_type":"ecoli-fbi-webhook"}'
+          -d '{"event_type":"ecoli-fbi-webhook"}' \
+          --write-out "%{http_code}" -o /dev/null)
+          
+          echo "Status Code: $response"
+
+          if [[ "$response" != *"204"* ]]; then
+            echo "Failed to trigger workflow: $response"
+            exit 1
+          fi
